### ISSUE TITLE
Nothing Returning

### ISSUE THREAD

**Issue by Al-Mond** [SMSAgentSoftware/MEM#2]
Hello! 

Just this week, the call to the graph API is returning nothing. I'm trying to figure out if this is something we have misconfigured or if there is something up with the graph API. I have noticed that in our configuration if I click through Intune -> Reports -> Endpoint Analytics -> Work from anywhere, I see data on the overview page but nothing when I click the Windows tab. Just curious if anyone is seeing the same.

Thanks!

**Comment by SMSAgentSoftware** [comment]
I noticed the same thing today and raised a support case with Microsoft. Waiting on their investigation...

**Comment by Al-Mond** [comment]
> I noticed the same thing today and raised a support case with Microsoft. Waiting on their investigation...

Perfect, thanks! This happened right around the time we were adjusting roles and scopes and I was concerned we might have done something wrong.

**Comment by SMSAgentSoftware** [comment]
Looks like MS have resolved this now.

**Comment by Al-Mond** [comment]
> Looks like MS have resolved this now.

Perfect, thanks for the follow up!
