### ISSUE TITLE
Windows 11 readiness status Unknown

### ISSUE THREAD

**Issue by Al-Mond** [SMSAgentSoftware/MEM#3]
Hello!

It looks like all the systems in our Intune tenant that aren't upgraded or Not Capable or showing their Windows 11 readiness status
as Unknown. I was curious if you are seeing this as well. Seems like another issue with the backend, though.

Thanks again!
    -Al

**Comment by SMSAgentSoftware** [comment]
As I recall, this was a temporary service issue that was fixed soon after.

**Comment by Al-Mond** [comment]
Yup! I think this one took a few weeks for MS to sort out. Sorry, I should have replied here when they fixed it. Thanks for the excellent utility!
