### ISSUE TITLE
Microsoft Update Health Tools - Detection script

### ISSUE THREAD

**Issue by Strykar-DC** [SMSAgentSoftware/MEM#4]
Hello,

It seems like the Detection script is not working correctly. 

It says "With Issues" even if its installed on the computer. I don't think it matters which Health tool version is installed. The are all latest version (3.67) and using the same registry path/keys.

**Comment by ghost** [comment]
I can't reproduce this on my machines.

What happens if you run the detection script manually?

Any chance the proactive remediation is set to run the script in 32 bit mode? I've done that to myself a number of times.

**Comment by Strykar-DC** [comment]
Ahh.. The 64-bit powershell. So silly of me... 

All good. The script is working :)
