### ISSUE TITLE
Add Delivery Optimization

### ISSUE THREAD

**Issue by sranga80** [SMSAgentSoftware/MEM#5]
is it possible to add delivery optimization status to this custom inventory?

**Comment by SMSAgentSoftware** [comment]
I decided to not to include DO in this particular report. If you're using UC / WUfB reports from MS, I'd recommend this community solution: https://msendpointmgr.com/2022/03/25/delivery-optimization-configuration-monitoring/

**Comment by sranga80** [comment]
Okay. let me try to  add the information.
